### ISSUE TITLE
As a player, I don’t want the actual code recorded. E.g., so I can scan and score my vaccine passport. (US 08.01.01)

### ISSUE THREAD

**Issue by WillQizza** [CMPUT301W23T09/QRHunter#14]
As a player, I don’t want the actual code recorded. E.g., so I can scan and score my vaccine passport.

## Acceptance Criteria
- [ ] Compute and store hash of code instead of the actual code

**Comment by jmmabanta** [comment]
Completed in [jmmabanta/qr-scan](https://github.com/CMPUT301W23T09/QRHunter/tree/jmmabanta/qr-scan).
Codes are hashed using SHA256
