### ISSUE TITLE
As a player, I want to be able to decline recording geolocation for privacy reasons. (US 08.02.01)

### ISSUE THREAD

**Issue by WillQizza** [CMPUT301W23T09/QRHunter#16]
As a player, I want to be able to decline recording geolocation for privacy reasons.

## Acceptance Criteria
- [x] Allow user to toggle between allowing and not allowing geolocation

**Comment by jmmabanta** [comment]
Everytime the QR Code is scanned, a checkbox is presented to the player if they want to record the code's geolocation.
