### ISSUE TITLE
As an owner, I don’t want to store big images online. (US 09.01.01)

### ISSUE THREAD

**Issue by WillQizza** [CMPUT301W23T09/QRHunter#19]
As an owner, I don’t want to store big images online.

## Acceptance Criteria
- [ ] After taking a photo, check image size
- [ ] Alert user if the size is too large
- [ ] If the size is too large, prompt user to indicate whether they want the image stored online
- [ ] Store the image online as per user input
- [ ] Image is <100KB

**Comment by jmmabanta** [comment]
I feel that we should get rid of criteria 2-3 and we just automatically compress the image.
