### ISSUE TITLE
UI Mockups and Storyboarding

### ISSUE THREAD

**Issue by jmmabanta** [CMPUT301W23T09/QRHunter#24]
# UI Mockup Checklist
- [x] Landing (Login for first time users)
- [x] Home
    - [x] Scanning a code
- [x] (My) User Profile
    - [x] See highest and lowest scoring QR codes
    - [x] See total points & total number of codes scanned
    - [x] See estimated rank
- [x] QR Code Information
- [x] Leaderboard
    - [x] Search for other players
    - [x] Show user ranking among other players
- [x] Viewing other user profiles
- [x] Map of QR Codes
    - ~~[ ] Search for QR Codes at specific geolocation~~
    - [x] Show nearby QR Codes

# UI Storyboard Checklist
- [x] Opening the app (first-time and existing users)
- [x] Scanning a QR Code
    - [x] Taking location picture
    - [x] Consenting to geolocation recording
    - [x] Adding to account
- [x] Viewing own user profile
- [x] Selecting a QR Code
    - [x] Seeing visual representation and QR Code's name
    - [x] Seeing other users who've scanned that code 
    - [x] Seeing code's geolocation
    - [x] Seeing and leaving comments
- [x] Browsing Leaderboard
    - [x] Showing different rankings (by total points or by number of codes scanned)
    - [x] Viewing other user's profile (along with the QR Codes they've scanned)
    - [x] Seeing other user's contact info
- [x] Browsing map
    - ~~[ ] Searching for QR codes at location~~
    - [x] Showing nearby codes
    - [x] Selecting QR code from map for more information

**Comment by WillQizza** [comment]
Double checking that all criterias are met.

## Player
- [ ] #3 
- [ ] #5 
- [ ] #8 
- [ ] #18 
- [ ] #17 
- [ ] #15 
- [ ] #6 

## Game QR Codes
- [ ] #20 
- [ ] #9 
- [ ] #12 
- [ ] #10 
- [ ] #13 
- [ ] #1 

## Player Profile
- [ ] #7 
- [ ] #22 

## Searching
- [ ] #4 
- [ ] #23 

## Location
- [ ] #2 

## Scoring
- [ ] #11 
- [ ] #21 

## Privacy
- [ ] #14 
- [ ] #16 

# Owner
- [ ] #19
