### ISSUE TITLE
As a player, I want to remove QR codes from my account. (US 01.03.01)

### ISSUE THREAD

**Issue by WillQizza** [CMPUT301W23T09/QRHunter#8]
As a player, I want to remove QR codes from my account.

## Acceptance Criteria
- [ ] There should be a list of QR codes that the player scanned that is accessible
- [ ] It should be possible to remove a QR code from a user's account & score
- [ ] Users should be prompted to confirm they want to remove a QR code

**Comment by jmmabanta** [comment]
What's are the incentive(s) of deleting a QR code from account?
